tasks:
  - name: Doc Genrator Server
    init: bash ./deploy.sh
    env:
      DATABASE_URL: "postgresql://postgresql:yoursupersecret@localhost:10021/templaterdb?schema=public"

ports:
  - port: 8000
    onOpen: ignore
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: public
  - port: 5001
    onOpen: ignore
    visibility: public
  - port: 10021
    onOpen: ignore
    visibility: public
  - port: 10022
    onOpen: ignore
    visibility: public
  - port: 3007
    onOpen: ignore
    visibility: public